# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np
vec = np.zeros(100)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
import numpy as np
vec = np.ones(100)
print(vec)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
import numpy as np
vec = np.full(100, 3)
print(vec)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Как получить документацию о функции numpy.add из командной строки?

In [7]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [109]:
m = np.arange(16).reshape(4,4)
m[[0,1]] = m[[1,0]]
print(m)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Создать вектор со значениями от 10 до 100

In [4]:
import numpy as np
a = np.arange(10, 101) 
print(a)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### 7. Развернуть вектор (первый становится последним)

In [7]:
import numpy as np
vec = np.arange(10)
vec = vec[::-1]
print(vec)

[9 8 7 6 5 4 3 2 1 0]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [12]:
import numpy as np
m = np.arange(16).reshape(4,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

#### 10. Создать 3x3 единичную матрицу

In [12]:
import numpy as np
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [15]:
m = np.random.random((3,3,3))
print(m)

[[[0.03163175 0.24700759 0.50694722]
  [0.27676186 0.60368981 0.52813487]
  [0.61258095 0.43583613 0.26798632]]

 [[0.39037194 0.51098682 0.15088825]
  [0.51867624 0.32345656 0.19910327]
  [0.45637909 0.54266634 0.58322783]]

 [[0.10332939 0.14857089 0.85772011]
  [0.88209788 0.00350472 0.99312967]
  [0.17222765 0.02395355 0.66946456]]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [21]:
m = np.random.random((10, 10))
Mmin, Mmax = m.min(), m.max()
print(Mmin, Mmax)

0.03504802457077438 0.9908989323232639


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [20]:
vec = np.random.random(30)
m = vec.mean()
print(m)

0.4509503468115313


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [26]:
m = np.ones((10,10))
m[1:-1,1:-1] = 0
print(m)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [66]:
vec = np.arange(5)
np.random.shuffle(vec)
print(vec)

[2 1 3 4 0]


#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [34]:
m = np.diag(np.arange(1, 5), k=1)
print(m)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [47]:
m = np.zeros((8,8), dtype=int)
m[1::2,::2] = 1
m[::2,1::2] = 1
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [48]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [53]:
m = np.tile(np.array([[1,0], [0,1]]), (4, 4))
print(m)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [56]:
m = np.dot(np.ones((5,3)), np.ones((3,2)))
print(m)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [70]:
m = np.arange(11)
m[(3 < m) & (m < 8)] *= -1
print(m)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [71]:
m = np.zeros((5,5))
m += np.arange(5)
print(m)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24. Есть генератор, сделать с его помощью массив

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [77]:
m = np.linspace(0,1,12)[1:-1]
print(m)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26. Отсортировать вектор

In [83]:
m = np.random.random(10)
m.sort()
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [89]:
a = np.random.randint(0,6,5)
b = np.random.randint(0,6,5)
print(a)
print(b)
isEqual = np.allclose(a,b)
print(isEqual)

[5 2 3 1 1]
[0 1 1 1 0]
False


#### 28. Сделать массив неизменяемым

In [92]:
m = np.arange(10)
m.flags.writeable = False
print(m)
m[1] = 1

[0 1 2 3 4 5 6 7 8 9]


ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

#### 30. Заменить максимальный элемент на ноль

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [93]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [94]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 34. Напечатать все значения в массиве

#### 35. Найти ближайшее к заданному значению число в заданном массиве

#### 36. Преобразовать массив из float в int

#### 37. Каков эквивалент функции enumerate для numpy массивов?

#### 38. Случайно расположить p элементов в 2D массив

#### 39. Отнять среднее из каждой строки в матрице

In [117]:
m = np.random.rand(5, 10)
m2 = m - m.mean(axis=1, keepdims=True)
print(m)
print(m2)

[[0.91497143 0.65045125 0.15104222 0.72419131 0.3278285  0.6172926
  0.97946381 0.49192416 0.84439859 0.07496802]
 [0.13543924 0.01898453 0.94660755 0.95716129 0.78244313 0.27851427
  0.9170983  0.15237084 0.35060609 0.65972851]
 [0.04174015 0.93279088 0.84912544 0.10629781 0.80935399 0.95423897
  0.80853411 0.83103783 0.39295978 0.93048969]
 [0.63366095 0.22868228 0.88704493 0.21188376 0.6581911  0.53587435
  0.58803706 0.11619929 0.11900999 0.68723465]
 [0.50130482 0.64912353 0.60198048 0.4024435  0.64569978 0.59127237
  0.41907997 0.77230318 0.28002958 0.80828394]]
[[ 0.33731824  0.07279806 -0.42661097  0.14653812 -0.24982469  0.03963941
   0.40181062 -0.08572903  0.26674541 -0.50268517]
 [-0.38445613 -0.50091085  0.42671217  0.43726592  0.26254775 -0.2413811
   0.39720292 -0.36752453 -0.16928928  0.13983314]
 [-0.62391672  0.26713402  0.18346858 -0.55935906  0.14369713  0.28858211
   0.14287724  0.16538096 -0.27269709  0.26483283]
 [ 0.16707912 -0.23789956  0.42046309 -0.25469807  

#### 40. Отсортировать матрицу по n-ому столбцу

In [102]:
m = np.random.randint(0,50,(3,3))
n = 0
print(m)
print(m[m[:,n].argsort()])

[[10  5 25]
 [ 8 17 41]
 [23  6  0]]
[[ 8 17 41]
 [10  5 25]
 [23  6  0]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [103]:
m = np.random.randint(0,3,(3,10))
print((~m.any(axis=0)).any())

False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям